apiVersion: v1
kind: Secret
metadata:
  name: inngest-secret-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: inngest
    instance: "${INSTANCE_ID}"
type: Opaque
stringData:
  INNGEST_SIGNING_KEY: "${INNGEST_SIGNING_KEY}"
  INNGEST_EVENT_KEY: "${INNGEST_EVENT_KEY}"
