apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.28.0.20:9090
    uid: prometheus
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://172.28.0.30:3100
    uid: loki
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://172.28.0.40:16686
    uid: jaeger
    editable: true