tls:
  certificates:
  - certFile: /certs/scaibu.otel.pem
    keyFile: /certs/scaibu.otel-key.pem
  - certFile: /certs/scaibu.prometheus.pem
    keyFile: /certs/scaibu.prometheus-key.pem
  - certFile: /certs/scaibu.loki.pem
    keyFile: /certs/scaibu.loki-key.pem
  - certFile: /certs/scaibu.jaeger.pem
    keyFile: /certs/scaibu.jaeger-key.pem
  - certFile: /certs/scaibu.alertmanager.pem
    keyFile: /certs/scaibu.alertmanager-key.pem
  - certFile: /certs/scaibu.grafana.pem
    keyFile: /certs/scaibu.grafana-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/scaibu.otel.pem
        keyFile: /certs/scaibu.otel-key.pem
