apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: inngest-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: inngest
    instance: "${INSTANCE_ID}"
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`inngest-${INSTANCE_ID}.localhost`)
    kind: Rule
    services:
    - name: inngest-${INSTANCE_ID}
      port: 8288
    middlewares:
    - name: security-headers-${INSTANCE_ID}
    - name: rate-limit-${INSTANCE_ID}
    - name: compression-${INSTANCE_ID}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: inngest-scaibu-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: inngest
    instance: "${INSTANCE_ID}"
spec:
  entryPoints:
    - traefik
  routes:
  - match: Host(`scaibu.inngest`)
    kind: Rule
    services:
    - name: inngest-${INSTANCE_ID}
      port: 8288
    middlewares:
    - name: security-headers-${INSTANCE_ID}
