apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: traefik
    instance: "${INSTANCE_ID}"
spec:
  entryPoints:
    - traefik
  routes:
  - match: Host(`traefik-${INSTANCE_ID}.localhost`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: security-headers-${INSTANCE_ID}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-scaibu-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: traefik
    instance: "${INSTANCE_ID}"
spec:
  entryPoints:
    - traefik
  routes:
  - match: Host(`scaibu.traefik`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: security-headers-${INSTANCE_ID}
