tls:
  certificates:
  - certFile: /certs/scaibu.neo4j.pem
    keyFile: /certs/scaibu.neo4j-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/scaibu.neo4j.pem
        keyFile: /certs/scaibu.neo4j-key.pem
