tls:
  certificates:
  - certFile: /certs/scaibu.qdrant.pem
    keyFile: /certs/scaibu.qdrant-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/scaibu.qdrant.pem
        keyFile: /certs/scaibu.qdrant-key.pem
