apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: alertmanager
    instance: "${INSTANCE_ID}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
      instance: "${INSTANCE_ID}"
  template:
    metadata:
      labels:
        app: alertmanager
        instance: "${INSTANCE_ID}"
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        ports:
        - containerPort: 9093
          name: alertmanager
        command:
        - --config.file=/etc/alertmanager/alertmanager_config.yaml
        - --storage.path=/alertmanager

        resources:
          limits:
            memory: 128Mi
            cpu: 300m
          requests:
            memory: 64Mi
            cpu: 150m
        livenessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:9093/-/healthy
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:9093/-/healthy
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: alertmanager-data
          mountPath: /data
      volumes:
      - name: alertmanager-data
        persistentVolumeClaim:
          claimName: alertmanager-pvc-${INSTANCE_ID}
