apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-repo-server-instance
  template:
    metadata:
      labels:
        app: argocd-repo-server-instance
    spec:
      containers:
        - name: argocd-repo-server
          image: argoproj/argocd:latest
          env:
            - name: REPO_SERVER_PORT
              value: "{{REPO_SERVER_PORT}}"
            - name: INSTANCE_ID
              value: "{{INSTANCE_ID}}"
          args:
            - "argocd-repo-server"
          ports:
            - name: repo
              containerPort: {{REPO_SERVER_PORT}}
          volumeMounts:
            - name: argocd-repo-data
              mountPath: /var/argocd/repo
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"
            requests:
              memory: "128Mi"
              cpu: "0.5"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "netstat -an | grep {{REPO_SERVER_PORT}} || exit 1"
            initialDelaySeconds: 40
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
      volumes:
        - name: argocd-repo-data
          persistentVolumeClaim:
            claimName: argocd-repo-pvc
