apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: ClusterIP
  selector:
    app: grafana-instance
  ports:
    - name: http
      port: {{GRAFANA_PORT}}
      targetPort: {{GRAFANA_PORT}}
