apiVersion: v1
kind: Service
metadata:
  name: inngest-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: inngest
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 8288
    targetPort: 8288
    protocol: TCP
    name: inngest
  selector:
    app: inngest
    instance: "${INSTANCE_ID}"
