apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  type: ClusterIP
  selector:
    app: jaeger-instance
  ports:
    - name: http
      port: {{HTTP_PORT}}
      targetPort: {{HTTP_PORT}}
    - name: otlp-grpc
      port: {{OTLP_GRPC_PORT}}
      targetPort: {{OTLP_GRPC_PORT}}
    - name: otlp-http
      port: {{OTLP_HTTP_PORT}}
      targetPort: {{OTLP_HTTP_PORT}}
    - name: grpc
      port: {{GRPC_PORT}}
      targetPort: {{GRPC_PORT}}
    - name: admin
      port: {{ADMIN_PORT}}
      targetPort: {{ADMIN_PORT}}
    - name: zipkin
      port: {{ZIPKIN_PORT}}
      targetPort: {{ZIPKIN_PORT}}
