apiVersion: v1
kind: Service
metadata:
  name: loki-${INSTANCE_ID}
  labels:
    app: loki
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: loki
  selector:
    app: loki
    instance: "${INSTANCE_ID}"
