apiVersion: v1
kind: Service
metadata:
  name: loki-service
spec:
  type: ClusterIP
  selector:
    app: loki-instance
  ports:
    - name: http
      port: {{HTTP_PORT}}
      targetPort: {{HTTP_PORT}}
    - name: grpc
      port: {{GRPC_PORT}}
      targetPort: {{GRPC_PORT}}
