apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: mongodb-instance
  ports:
    - name: db
      port: {{MONGO_PORT}}
      targetPort: {{MONGO_PORT}}
