apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: ClusterIP
  selector:
    app: mongo-express-instance
  ports:
    - name: http
      port: {{UI_PORT}}
      targetPort: {{UI_PORT}}
