apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-${INSTANCE_ID}
  labels:
    app: mongoexpress
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: mongoexpress
  selector:
    app: mongoexpress
    instance: "${INSTANCE_ID}"
