apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-${INSTANCE_ID}
  labels:
    app: mongoexpress
    instance: "${INSTANCE_ID}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
      instance: "${INSTANCE_ID}"
  template:
    metadata:
      labels:
        app: mongoexpress
        instance: "${INSTANCE_ID}"
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express:latest
        ports:
        - containerPort: 8081
          name: mongoexpress
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "MongoPassword123!"
        resources:
          limits:
            memory: 256Mi
            cpu: 300m
          requests:
            memory: 128Mi
            cpu: 150m
        livenessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:8081
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:8081
          initialDelaySeconds: 10
          periodSeconds: 10
