apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  type: ClusterIP
  selector:
    app: neo4j-instance
  ports:
    - name: http
      port: {{HTTP_PORT}}
      targetPort: {{HTTP_PORT}}
    - name: bolt
      port: {{BOLT_PORT}}
      targetPort: {{BOLT_PORT}}
