apiVersion: v1
kind: Service
metadata:
  name: neo4j-${INSTANCE_ID}
  labels:
    app: neo4j
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 7474
    targetPort: 7474
    protocol: TCP
    name: neo4j
  selector:
    app: neo4j
    instance: "${INSTANCE_ID}"
