apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: neo4j
    instance: "${INSTANCE_ID}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
      instance: "${INSTANCE_ID}"
  template:
    metadata:
      labels:
        app: neo4j
        instance: "${INSTANCE_ID}"
    spec:
      containers:
      - name: neo4j
        image: neo4j:latest
        ports:
        - containerPort: 7474
          name: neo4j
        - name: NEO4J_AUTH
          value: "neo4j/password"
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
        livenessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:7474
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:7474
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc-${INSTANCE_ID}
