apiVersion: v1
kind: Service
metadata:
  name: otel-collector-${INSTANCE_ID}
  labels:
    app: otel-collector
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otel-collector
  selector:
    app: otel-collector
    instance: "${INSTANCE_ID}"
