apiVersion: v1
kind: Service
metadata:
  name: promtail-${INSTANCE_ID}
  labels:
    app: promtail
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: promtail
  selector:
    app: promtail
    instance: "${INSTANCE_ID}"
