apiVersion: v1
kind: Service
metadata:
  name: promtail-service
spec:
  type: ClusterIP
  selector:
    app: promtail-instance
  ports:
    - name: http
      port: {{PROMTAIL_PORT}}
      targetPort: {{PROMTAIL_PORT}}
