apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: promtail
    instance: "${INSTANCE_ID}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
      instance: "${INSTANCE_ID}"
  template:
    metadata:
      labels:
        app: promtail
        instance: "${INSTANCE_ID}"
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:latest
        ports:
        - containerPort: 9080
          name: promtail
        command:
        - -config.file=/etc/promtail/config.yml

        resources:
          limits:
            memory: 256Mi
            cpu: 300m
          requests:
            memory: 128Mi
            cpu: 150m
        livenessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:9080/ready
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - wget
            - --no-verbose
            - --tries=1
            - --spider
            - http://localhost:9080/ready
          initialDelaySeconds: 10
          periodSeconds: 10
