apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: ClusterIP
  selector:
    app: prometheus-instance
  ports:
    - name: http
      port: {{HOST_PORT}}
      targetPort: 9090
