apiVersion: v1
kind: Service
metadata:
  name: qdrant-${INSTANCE_ID}
  labels:
    app: qdrant
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 6333
    targetPort: 6333
    protocol: TCP
    name: qdrant
  selector:
    app: qdrant
    instance: "${INSTANCE_ID}"
