apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  type: ClusterIP
  selector:
    app: qdrant-instance
  ports:
    - name: http
      port: {{HTTP_PORT}}
      targetPort: {{HTTP_PORT}}
    - name: grpc
      port: {{GRPC_PORT}}
      targetPort: {{GRPC_PORT}}
