apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: prometheus
    instance: "${INSTANCE_ID}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: mongodb
    instance: "${INSTANCE_ID}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: neo4j
    instance: "${INSTANCE_ID}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: qdrant
    instance: "${INSTANCE_ID}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
