apiVersion: v1
kind: Service
metadata:
  name: tempo-${INSTANCE_ID}
  labels:
    app: tempo
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 3200
    targetPort: 3200
    protocol: TCP
    name: tempo
  selector:
    app: tempo
    instance: "${INSTANCE_ID}"
