apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo-instance
  template:
    metadata:
      labels:
        app: tempo-instance
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          env:
            - name: TEMPO_HTTP_PORT
              value: "{{HTTP_PORT}}"
          ports:
            - name: http
              containerPort: 3200
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: grpc
              containerPort: 9095
            - name: zipkin
              containerPort: 9411
          volumeMounts:
            - name: tempo-data
              mountPath: /tmp/tempo
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /ready
              port: 3200
            initialDelaySeconds: 40
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
      volumes:
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-data-pvc
