apiVersion: v1
kind: Service
metadata:
  name: traefik-${INSTANCE_ID}
  namespace: ${NAMESPACE}
  labels:
    app: traefik
    instance: "${INSTANCE_ID}"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: web
  - port: 443
    targetPort: 443
    protocol: TCP
    name: websecure
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: dashboard
  selector:
    app: traefik
    instance: "${INSTANCE_ID}"

