apiVersion: v1
kind: Service
metadata:
  name: traefik-${INSTANCE_ID}
  labels:
    app: traefik
    instance: "${INSTANCE_ID}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: traefik
  selector:
    app: traefik
    instance: "${INSTANCE_ID}"
